export const ActionTypes = {

    CHANGE_FACILITY_NAME : 'CHANGE_FACILITY_NAME',
    CHANGE_FACILITY_CAR_TYPE : 'CHANGE_FACILITY_CAR_TYPE',
    CHANGE_EXPIRE_DATE : 'CHANGE_EXPIRE_DATE',
    CHANGE_FACILITY_MEMO : 'CHANGE_FACILITY_MEMO',

    NEW_FACILITY: "NEW_FACILITY",
    EDIT_FACILITY: "EDIT_FACILITY",
    CANCEL_EDIT_FACILITY: "CANCEL_EDIT_FACILITY",

    ADD_FACILITY: "ADD_FACILITY",
    SUCCESS_ADD_FACILITY: "SUCCESS_ADD_FACILITY",
    ERROR_ADD_FACILITY: "ERROR_ADD_FACILITY",

    SAVE_FACILITY: "SAVE_FACILITY",
    SUCCESS_SAVE_FACILITY: "SUCCESS_SAVE_FACILITY",
    ERROR_SAVE_FACILITY: "ERROR_SAVE_FACILITY",

    SUCCESS_GET_FACILITIES: "SUCCESS_GET_FACILITIES",
    ERROR_GET_FACILITIES: "ERROR_GET_FACILITIES",

    CANCEL_DELETE_FACILITY: "CANCEL_DELETE_FACILITY",
    CONFIRM_DELETE_FACILITY: "CONFIRM_DELETE_FACILITY",
    DELETE_FACILITY: "DELETE_FACILITY",
    SUCCESS_DELETE_FACILITY: "SUCCESS_DELETE_FACILITY",
    ERROR_DELETE_FACILITY: "ERROR_DELETE_FACILITY",


};