export const ActionTypes = {

    CHANGE_LOGIN_EMAIL : 'CHANGE_LOGIN_EMAIL',
    VALIDATE_LOGIN_EMAIL : 'VALIDATE_LOGIN_EMAIL',
    FINISH_LOGIN_EMAIL_VALIDATION : 'FINISH_LOGIN_EMAIL_VALIDATION',

    CHANGE_LOGIN_PASSWORD : 'CHANGE_LOGIN_PASSWORD',
    VALIDATE_LOGIN_PASSWORD : 'VALIDATE_LOGIN_PASSWORD',
    FINISH_LOGIN_PASSWORD_VALIDATION : 'FINISH_LOGIN_PASSWORD_VALIDATION',

    FETCH_LOGIN_STATE : 'FETCH_LOGIN_STATE',
    SUCCESS_FETCH_LOGIN_STATE : 'SUCCESS_FETCH_LOGIN_STATE',

    LOGIN : 'LOGIN',
    SUCCESS_LOGIN : 'SUCCESS_LOGIN',
    ERROR_LOGIN : 'ERROR_LOGIN',

    LOGOUT : 'LOGOUT',
    SUCCESS_LOGOUT : 'SUCCESS_LOGOUT',
    ERROR_LOGOUT : 'ERROR_LOGOUT',

};