
export const ActionTypes = {

    SUCCESS_GET_SCHEDULES: "SUCCESS_GET_SCHEDULES",
    ERROR_GET_SCHEDULES: "ERROR_GET_SCHEDULES",

    NEW_SCHEDULE: "NEW_SCHEDULE",
    ADD_SCHEDULE: "ADD_SCHEDULE",
    SUCCESS_ADD_SCHEDULE: "SUCCESS_ADD_SCHEDULE",
    ERROR_ADD_SCHEDULE: "ERROR_ADD_SCHEDULE",

    CHANGE_SELECTED_STAFF: "CHANGE_SELECTED_STAFF",
    CHANGE_SELECTED_CUSTOMER: "CHANGE_SELECTED_CUSTOMER",
    CHANGE_MEMO: "CHANGE_MEMO",
    CHANGE_SELECTED_RENTAL_REASON: "CHANGE_SELECTED_RENTAL_REASON",
    CHANGE_START: "CHANGE_START",
    CHANGE_END: "CHANGE_END",
    CANCEL_EDIT_SCHEDULE: "CANCEL_EDIT_SCHEDULE",

    EDIT_SCHEDULE: "EDIT_SCHEDULE",
    SAVE_SCHEDULE: "SAVE_SCHEDULE",
    SUCCESS_SAVE_SCHEDULE: "SUCCESS_SAVE_SCHEDULE",
    ERROR_SAVE_SCHEDULE: "ERROR_SAVE_SCHEDULE",

    CANCEL_DELETE_SCHEDULE: "CANCEL_DELETE_SCHEDULE",
    CONFIRM_DELETE_SCHEDULE: "CONFIRM_DELETE_SCHEDULE",
    DELETE_SCHEDULE: "DELETE_SCHEDULE",
    SUCCESS_DELETE_SCHEDULE: "SUCCESS_DELETE_SCHEDULE",
    ERROR_DELETE_SCHEDULE: "ERROR_DELETE_SCHEDULE",

    CHANGE_FILTER_TYPE: "CHANGE_FILTER_TYPE",
    TOGGLE_CAR_LIST: "TOGGLE_CAR_LIST",

};