
export const ActionTypes = {

    LOCATION_CHANGE: "@@router/LOCATION_CHANGE",

    CHANGE_EMAIL : 'CHANGE_EMAIL',
    VALIDATE_EMAIL : 'VALIDATE_EMAIL',
    FINISH_EMAIL_VALIDATION : 'FINISH_EMAIL_VALIDATION',

    PASSWORD_FOCUSED_ONCE : 'PASSWORD_FOCUSED_ONCE',
    CHANGE_PASSWORD : 'CHANGE_PASSWORD',
    VALIDATE_PASSWORD : 'VALIDATE_PASSWORD',
    FINISH_PASSWORD_VALIDATION : 'FINISH_PASSWORD_VALIDATION',

    PASSWORD_CONFIRM_FOCUSED_ONCE : 'PASSWORD_CONFIRM_FOCUSED_ONCE',
    CHANGE_PASSWORD_CONFIRM : 'CHANGE_PASSWORD_CONFIRM',
    VALIDATE_PASSWORD_CONFIRM : 'VALIDATE_PASSWORD_CONFIRM',
    FINISH_PASSWORD_CONFIRM_VALIDATION : 'FINISH_PASSWORD_CONFIRM_VALIDATION',

    CHANGE_LOGIN_EMAIL : 'CHANGE_LOGIN_EMAIL',
    VALIDATE_LOGIN_EMAIL : 'VALIDATE_LOGIN_EMAIL',
    FINISH_LOGIN_EMAIL_VALIDATION : 'FINISH_LOGIN_EMAIL_VALIDATION',

    CHANGE_LOGIN_PASSWORD : 'CHANGE_LOGIN_PASSWORD',
    VALIDATE_LOGIN_PASSWORD : 'VALIDATE_LOGIN_PASSWORD',
    FINISH_LOGIN_PASSWORD_VALIDATION : 'FINISH_LOGIN_PASSWORD_VALIDATION',

    FETCH_LOGIN_STATE : 'FETCH_LOGIN_STATE',
    SUCCESS_FETCH_LOGIN_STATE : 'SUCCESS_FETCH_LOGIN_STATE',

    CREATE_ACCOUNT : 'CREATE_ACCOUNT',
    SUCCESS_CREATE_ACCOUNT : 'SUCCESS_CREATE_ACCOUNT',
    ERROR_CREATE_ACCOUNT : 'ERROR_CREATE_ACCOUNT',
    LOGIN : 'LOGIN',
    SUCCESS_LOGIN : 'SUCCESS_LOGIN',
    ERROR_LOGIN : 'ERROR_LOGIN',

    LOGOUT : 'LOGOUT',
    SUCCESS_LOGOUT : 'SUCCESS_LOGOUT',
    ERROR_LOGOUT : 'ERROR_LOGOUT',

    CHANGE_CUSTOMER_NAME : 'CHANGE_CUSTOMER_NAME',
    CHANGE_CUSTOMER_DRIVER_TYPE : 'CHANGE_CUSTOMER_DRIVER_TYPE',
    CHANGE_CUSTOMER_MEMO : 'CHANGE_CUSTOMER_MEMO',

    NEW_CUSTOMER: "NEW_CUSTOMER",
    EDIT_CUSTOMER: "EDIT_CUSTOMER",
    CANCEL_EDIT_CUSTOMER: "CANCEL_EDIT_CUSTOMER",

    ADD_CUSTOMER: "ADD_CUSTOMER",
    SUCCESS_ADD_CUSTOMER: "SUCCESS_ADD_CUSTOMER",
    ERROR_ADD_CUSTOMER: "ERROR_ADD_CUSTOMER",

    SAVE_CUSTOMER: "SAVE_CUSTOMER",
    SUCCESS_SAVE_CUSTOMER: "SUCCESS_SAVE_CUSTOMER",
    ERROR_SAVE_CUSTOMER: "ERROR_SAVE_CUSTOMER",

    SUCCESS_GET_CUSTOMERS: "SUCCESS_GET_CUSTOMERS",
    ERROR_GET_CUSTOMERS: "ERROR_GET_CUSTOMERS",

    CANCEL_DELETE_CUSTOMER: "CANCEL_DELETE_CUSTOMER",
    CONFIRM_DELETE_CUSTOMER: "CONFIRM_DELETE_CUSTOMER",
    DELETE_CUSTOMER: "DELETE_CUSTOMER",
    SUCCESS_DELETE_CUSTOMER: "SUCCESS_DELETE_CUSTOMER",
    ERROR_DELETE_CUSTOMER: "ERROR_DELETE_CUSTOMER",

    CHANGE_STAFF_NAME : 'CHANGE_STAFF_NAME',
    CHANGE_STAFF_MEMO : 'CHANGE_STAFF_MEMO',

    NEW_STAFF: "NEW_STAFF",
    EDIT_STAFF: "EDIT_STAFF",
    CANCEL_EDIT_STAFF: "CANCEL_EDIT_STAFF",

    ADD_STAFF: "ADD_STAFF",
    SUCCESS_ADD_STAFF: "SUCCESS_ADD_STAFF",
    ERROR_ADD_STAFF: "ERROR_ADD_STAFF",

    SAVE_STAFF: "SAVE_STAFF",
    SUCCESS_SAVE_STAFF: "SUCCESS_SAVE_STAFF",
    ERROR_SAVE_STAFF: "ERROR_SAVE_STAFF",

    SUCCESS_GET_STAFFS: "SUCCESS_GET_STAFFS",
    ERROR_GET_STAFFS: "ERROR_GET_STAFFS",

    CANCEL_DELETE_STAFF: "CANCEL_DELETE_STAFF",
    CONFIRM_DELETE_STAFF: "CONFIRM_DELETE_STAFF",
    DELETE_STAFF: "DELETE_STAFF",
    SUCCESS_DELETE_STAFF: "SUCCESS_DELETE_STAFF",
    ERROR_DELETE_STAFF: "ERROR_DELETE_STAFF",

    CHANGE_FACILITY_NAME : 'CHANGE_FACILITY_NAME',
    CHANGE_FACILITY_CAR_TYPE : 'CHANGE_FACILITY_CAR_TYPE',
    CHANGE_EXPIRE_DATE : 'CHANGE_EXPIRE_DATE',
    CHANGE_FACILITY_MEMO : 'CHANGE_FACILITY_MEMO',

    NEW_FACILITY: "NEW_FACILITY",
    EDIT_FACILITY: "EDIT_FACILITY",
    CANCEL_EDIT_FACILITY: "CANCEL_EDIT_FACILITY",

    ADD_FACILITY: "ADD_FACILITY",
    SUCCESS_ADD_FACILITY: "SUCCESS_ADD_FACILITY",
    ERROR_ADD_FACILITY: "ERROR_ADD_FACILITY",

    SAVE_FACILITY: "SAVE_FACILITY",
    SUCCESS_SAVE_FACILITY: "SUCCESS_SAVE_FACILITY",
    ERROR_SAVE_FACILITY: "ERROR_SAVE_FACILITY",

    SUCCESS_GET_FACILITIES: "SUCCESS_GET_FACILITIES",
    ERROR_GET_FACILITIES: "ERROR_GET_FACILITIES",

    CANCEL_DELETE_FACILITY: "CANCEL_DELETE_FACILITY",
    CONFIRM_DELETE_FACILITY: "CONFIRM_DELETE_FACILITY",
    DELETE_FACILITY: "DELETE_FACILITY",
    SUCCESS_DELETE_FACILITY: "SUCCESS_DELETE_FACILITY",
    ERROR_DELETE_FACILITY: "ERROR_DELETE_FACILITY",

    SUCCESS_GET_SCHEDULES: "SUCCESS_GET_SCHEDULES",
    ERROR_GET_SCHEDULES: "ERROR_GET_SCHEDULES",

    NEW_SCHEDULE: "NEW_SCHEDULE",
    ADD_SCHEDULE: "ADD_SCHEDULE",
    SUCCESS_ADD_SCHEDULE: "SUCCESS_ADD_SCHEDULE",
    ERROR_ADD_SCHEDULE: "ERROR_ADD_SCHEDULE",

    CHANGE_SELECTED_STAFF: "CHANGE_SELECTED_STAFF",
    CHANGE_SELECTED_CUSTOMER: "CHANGE_SELECTED_CUSTOMER",
    CHANGE_MEMO: "CHANGE_MEMO",
    CHANGE_SELECTED_RENTAL_REASON: "CHANGE_SELECTED_RENTAL_REASON",
    CHANGE_START: "CHANGE_START",
    CHANGE_END: "CHANGE_END",
    CANCEL_EDIT_SCHEDULE: "CANCEL_EDIT_SCHEDULE",

    EDIT_SCHEDULE: "EDIT_SCHEDULE",
    SAVE_SCHEDULE: "SAVE_SCHEDULE",
    SUCCESS_SAVE_SCHEDULE: "SUCCESS_SAVE_SCHEDULE",
    ERROR_SAVE_SCHEDULE: "ERROR_SAVE_SCHEDULE",

    CANCEL_DELETE_SCHEDULE: "CANCEL_DELETE_SCHEDULE",
    CONFIRM_DELETE_SCHEDULE: "CONFIRM_DELETE_SCHEDULE",
    DELETE_SCHEDULE: "DELETE_SCHEDULE",
    SUCCESS_DELETE_SCHEDULE: "SUCCESS_DELETE_SCHEDULE",
    ERROR_DELETE_SCHEDULE: "ERROR_DELETE_SCHEDULE",

    CHANGE_FILTER_TYPE: "CHANGE_FILTER_TYPE",

    OPEN_SELECT: "OPEN_SELECT",
    CLOSE_SELECT: "CLOSE_SELECT",

    CLEAR_STATE: "CLEAR_STATE",

    TOGGLE_MENU: "TOGGLE_MENU",
};